package com.liang.blog.testAiModel;

import com.liang.blog.config.AiService;
import jakarta.annotation.Resource;
import org.junit.jupiter.api.Test;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.client.advisor.MessageChatMemoryAdvisor;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.deepseek.DeepSeekAssistantMessage;
import org.springframework.ai.deepseek.DeepSeekChatModel;
import org.springframework.ai.deepseek.DeepSeekChatOptions;
import org.springframework.ai.deepseek.api.DeepSeekApi;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import reactor.core.publisher.Flux;

@SpringBootTest
public class TestAi {

//    @Autowired
//    public TestAi(DeepSeekChatModel deepSeekChatModel) {
////        this.deepSeekChatModel = deepSeekChatModel;
//
//        chatClient = ChatClient.builder(deepSeekChatModel)
//                .defaultSystem("你是一个全能的博士")
//                .build();
//
//    }
//
//    private final ChatClient chatClient;

    // private final DeepSeekChatModel deepSeekChatModel;

    @Resource
    private AiService aiService;

    @Test
    public void test() {
        Flux<String> s = aiService.doChatWithStream("9.11 and 9.8, which is greater?");
        System.out.println(s);
    }


    @Test
    public void deepSeekReasonerExample() {
//        DeepSeekChatOptions promptOptions = DeepSeekChatOptions.builder()
//                .model(DeepSeekApi.ChatModel.DEEPSEEK_REASONER.getValue())
//                .build();
//        Prompt prompt = new Prompt("9.11 and 9.8, which is greater?", promptOptions);
//        ChatResponse response = deepSeekChatModel.call(prompt);
//
//        // Get the CoT content generated by deepseek-reasoner, only available when using deepseek-reasoner model
//        DeepSeekAssistantMessage deepSeekAssistantMessage = (DeepSeekAssistantMessage) response.getResult().getOutput();
//        String reasoningContent = deepSeekAssistantMessage.getReasoningContent();
//        System.out.println(reasoningContent);
//        String text = deepSeekAssistantMessage.getText();
    }
}
