spring:
  profiles:
    default: local
  application:
    name: liang-blog
  datasource:
    url: jdbc:mysql://localhost:3306/liang_blog?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${LIANG_BLOG_DB_USERNAME:}
    password: ${LIANG_BLOG_DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  ai:
    deepseek:
      api-key: ${LIANG_BLOG_DEEPSEEK_API_KEY}

server:
  port: 8080
  servlet:
    context-path: /api

app:
  security:
    jwt:
      issuer: liang-blog
      secret: change-this-secret
      access-token-ttl: PT2H

logging:
  level:
    root: INFO

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
